config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/show'
  get 'notes/new'
  get 'notes/edit'
  get 'notes/create'
  get 'notes/update'
  get 'notes/destroy'
  root 'companies#index', as: 'companies_index'

  resources :users
  post 'register', to: 'users#register'  

  resources :companies do
    resources :contact_people
    resources :notes
  end

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'register', to: 'sessions#register'
  get 'logout', to: 'sessions#destroy'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_company
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
    @notes = @company.notes
  end

  def show
  end

  def new
    @note = @company.notes.new
  end

  def edit
  end

  def create
    @note = @company.notes.new(note_params)

    @note.user_id = current_user.id
    @note.company_id = @company.id

    if @note.save
      redirect_to company_note_url, notice: 'Note was successfully created'
    else
      render :new
    end
  end

  def update
    if @note.update(note_params)
      redirect_to company_note_url, notice: 'Note was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    if @note.is_deleted != true
      @note.update(is_deleted: true)
      redirect_to company_notes_url, notice: 'Note was successfully deleted'
    else
      redirect_to company_notes_url, notice: 'Error: note wasn`t deleted'
    end
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_note
    @note = @company.notes.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:content)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/edit.html.haml
EDIT

app/views/notes/index.html.haml
.notes
  .row
    - if notice
      %p.alert.alert-info= notice
  .row
    %h3 Notes (#{@company.name})
    = link_to 'Add new note', new_company_note_path, class: "btn btn-primary add_new_note"

  .row.note_table_info.mt-1
    %table.table
      %thead.thead-dark
        %th{ scope: "col" } content
        %th{ scope: "col" } actions
      %tbody
        - @notes.each do |note|
          - if !note.is_deleted
            %tr
              %td.note_content= note.content
              %td
                = link_to 'Show', company_note_path(@company, note), class: "btn btn-warning show_note action_button"
                - if can? :update, @note
                  = link_to 'Edit', edit_company_note_path(@company, note), class: "btn btn-info edit_note action_button"
                - if can? :destroy, @note
                  = link_to 'Delete', company_note_path(@company, note), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger delete_note action_button"

app/views/notes/new.html.haml
NEW

app/views/notes/show.html.haml
SHOW