config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/show'
  get 'notes/new'
  get 'notes/edit'
  get 'notes/create'
  get 'notes/update'
  get 'notes/destroy'
  root 'companies#index', as: 'companies_index'

  resources :users
  post 'register', to: 'users#register'  

  resources :companies do
    resources :contact_people
    resources :notes
  end

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'register', to: 'sessions#register'
  get 'logout', to: 'sessions#destroy'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to  :industry
  belongs_to  :user
  has_many    :notes
  has_many    :contact_people

  validates :name, :nip, :address, :city, :industry_id, presence: true
  validates :nip, numericality: true

  scope :filter_by_industry, ->  (industry_id) { where(industry_id: industry_id) }
  scope :filter_by_date, -> (created_at) { where("DATE(created_at) = ?", created_at) }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  def index
    @companies = Company.paginate(page: params[:page], per_page: 5).where(is_deleted: false)

    @companies = @companies.filter_by_industry(params[:industry_id]) if params[:industry_id].present?
    @companies = @companies.filter_by_date(params[:created_at]) if params[:created_at].present?
  
    @industries = Industry.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
    @industries = Industry.all
  end

  def edit 
    @company = Company.find(params[:id])
    @industries = Industry.all
  end

  def create
    @company = Company.new(company_params)

    @company.user_id = current_user.id

    if @company.save
      redirect_to @company, notice: 'Company was successfully created'
    else
      @industries = Industry.all
      render :new
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated'
    else
      @industries = Industry.all
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])

    if @company.is_deleted != true
      @company.is_deleted = true
      @company.save
      redirect_to companies_url, notice: 'Company was successfuly deleted'
    else
      redirect_to companies_url, notice: 'Error: company wasn`t deleted'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :nip, :industry_id, :address, :city, :user_id, :is_deleted, :created_at)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= form_with(model: @company, local: true) do |form|
  - if @company.errors.any?
    .row.form_warnings
      %ul.alert.alert-danger.col-12
        - @company.errors.full_messages.each do |message|
          %li= message
    
  .field.form-group.row
    = form.label :name, 'Name', class: 'col-3 col-form-label'
    = form.text_field :name, size: 50, class: 'col-9 form-control'

  .field.form-group.row
    = form.label :nip, 'NIP', class: 'col-3 col-form-label'
    = form.text_field :nip, size: 10, class: 'col-9 form-control'

  .field.form-group.row
    = form.label :address, 'Address', class: 'col-3 col-form-label'
    = form.text_field :address, size: 50, class: 'col-9 form-control'

  .fiedl.form-group.row
    = form.label :city, 'City', class: 'col-3 col-form-label'
    = form.text_field :city, size: 50, class: 'col-9 form-control'

  .field.form-group.row
    = form.label :industry, 'Industry', class: 'col-3 col-form-label'
    = form.select(:industry_id, @industries.map { |industry| [industry.name, industry.id] }, {}, { class: 'col-9 form-control' })
    
  = form.hidden_field :is_deleted, value: false
  
  .actions.row.form-group.flex-float-right-content
    = form.submit class: 'btn btn-success submit_button'

app/views/companies/edit.html.haml
.company_edit
  .row
    - if notice
      %p.alert.alert-info= notice
  .row
    %h4= @company.name
  .row.user_edit_form
    = render 'form', company: @company
  .row
    = link_to 'Back', url_for(:back), :class => 'btn btn-secondary back_button'
    = link_to 'Companies', companies_path, :class => 'btn btn-primary redirect_companies_button ml-1'

app/views/companies/index.html.haml
.companies
  .row
    - if notice
      %p.alert.alert-info= notice
  .row.col-12
    %h3 Companies
  
    = link_to 'Add new company', new_company_path, class: "btn btn-primary add_new_company"
  
    .companies_filter_options.ml-4
      = form_with(url: companies_url, method: 'get', local: true, class: 'form-inline') do |form|
        .field.form-group
          = form.label :industry_id, 'Industry:', class: 'col-form-label'
          = form.select(:industry_id, @industries.map { |industry| [industry.name, industry.id] }, { prompt: '' }, class: 'form-control ml-1')
        .field.form-group.ml-2
          = form.label :created_at, 'Added:', class: 'col-form-label'
          = form.date_field :created_at, as: :date, value: form.object.try(:strftime, "%Y-%m-%d"), class: 'form-control ml-1'
        .actions.form-group.ml-2
          = form.submit 'Filter', class: 'btn btn-primary submit_button'

  .row.company_table_info.mt-1
    %table.table
      %thead.thead-dark
        %th{ scope: "col" } name
        %th{ scope: "col" } nip
        %th{ scope: "col" } industry
        %th{ scope: "col" } address
        %th{ scope: "col" } city
        %th{ scope: "col" } Added
        %th{ scope: "col" } contact
        %th{ scope: "col" } notes
        %th{ scope: "col" } actions
      %tbody
        - @companies.each do |company|
          - if !company.is_deleted
            %tr
              %td= company.name
              %td= company.nip
              %td= company.industry.name
              %td= company.address
              %td= company.city
              %td= company.created_at.to_date
              %td= link_to 'Contact', company_contact_people_url(company), class: 'btn btn-dark show_company_contact_people'
              %td= link_to 'Notes', company_notes_url(company), class: 'btn btn-success show_company_notes'
              %td
                = link_to 'Show', company, class: "btn btn-warning show_company action_button"
                - if can? :update, company
                  = link_to 'Edit', edit_company_path(company), class: "btn btn-info edit_company action_button"
                - if can? :destroy, company
                  = link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger delete_company action_button"
  .row.justify-content-center
    = will_paginate @companies

app/views/companies/new.html.haml
.companies_new
  .row
    - if notice
      %p.alert.alert-info= notice
  .row
    %h4 Add new company
  .row.company_new_form
    = render 'form', user: @company
  .row
    = link_to 'Back', url_for(:back), :class => 'btn btn-secondary back_button'

app/views/companies/show.html.haml
.company_show
  .row
    - if notice
      %p.alert.alert-info= notice
  .row
    %h4= @company.name
  .row.comapny_info
    %table.table.table-hover
      %tbody
        %tr
          %th{ scope: "row" } NIP
          %th{ scope: "row" }= @company.nip
        %tr
          %th{ scope: "row" } Industry
          %th{ scope: "row" }= @company.industry.name
        %tr 
          %th{ scope: "row" } Address
          %th{ scope: "row" }= @company.address
        %tr
          %th{ scope: "row" } City
          %th{ scope: "row" }= @company.city
  .row
    = link_to 'Back', url_for(:back), class: 'btn btn-secondary back_button'
    = link_to 'Companies', companies_path, class: 'btn btn-primary redirect_companies_button ml-1'