config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/show'
  get 'notes/new'
  get 'notes/edit'
  get 'notes/create'
  get 'notes/update'
  get 'notes/destroy'
  root 'companies#index', as: 'companies_index'

  resources :users
  post 'register', to: 'users#register'  

  resources :companies do
    resources :contact_people
    resources :notes
  end

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'register', to: 'sessions#register'
  get 'logout', to: 'sessions#destroy'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %title CRM - UAM
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'companies', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'contact_people', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'notes', media: 'all', 'data-turbolinks-track': 'reload'

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .wrapper
      - if current_user
        %nav.sidebar
          .sidebar-header
            %h3 CRM
          %ul.list-unstyled.components
            - if can? :read, @user
              %li
                = link_to 'Users', users_path
            %li
              = link_to 'Companies', companies_path
            %li
              = link_to 'Logout', logout_path, class: 'text-info'
      %main.content.d-flex.justify-content-center
        .col-12
          = yield